title: "Adil Mahmud"
description: "Portfolio, Blog, and Projects"
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Adil Mahmud"
  bio: "Researcher | ML & RL Enthusiast"
  email: "your.email@example.com"
